name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  # Build Jekyll site first
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build Jekyll Site
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site/

  # Run interaction and accessibility tests with Axe
  accessibility-tests:
    runs-on: ubuntu-latest
    needs: build
    name: Accessibility Tests
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site/
      - name: Setup Node.js for testing
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install test dependencies
        run: |
          npm init -y
          npm install --save-dev @axe-core/cli http-server browser-driver-manager
      - name: Setup Chrome and ChromeDriver
        run: npx browser-driver-manager install chrome
      - name: Start local server
        run: npx http-server _site -p 3000 &
      - name: Wait for server
        run: sleep 5
      - name: Run accessibility tests
        run: |
          npx axe http://localhost:3000 \
            --exit \
            --tags wcag2a,wcag2aa,wcag21aa \
            --rules color-contrast,image-alt,heading-order,landmark-one-main,page-has-heading-one,region \
            --timeout 30000

  # Run user flow tests with Cypress
  cypress-tests:
    runs-on: ubuntu-latest
    needs: build
    name: User Flow Tests
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Cypress
        run: |
          npm init -y
          npm install --save-dev cypress http-server
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config-file: test/cypress.config.js
          start: npx http-server _site -p 3000
          wait-on: 'http://localhost:3000'
          browser: chrome

  # Deploy to Azure Static Web Apps only after tests pass
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    needs: [build, accessibility-tests, cypress-tests]
    name: Deploy to Azure
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site/
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_ROCK_04F54D003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "_site" # Pre-built Jekyll site location
          api_location: "" # Api source code path - optional
          skip_app_build: true # Skip automatic build since we're building Jekyll manually
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_ROCK_04F54D003 }}
          action: "close"
