# .github/workflows/ui-tests.yml
name: 'UI Tests'

on: push

jobs:
  # Build Jekyll site first
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jekyll-site
          path: _site/

  # Run interaction and accessibility tests with Axe
  interaction-and-accessibility:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: jekyll-site
          path: _site/
      - name: Setup Node.js for testing
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install test dependencies
        run: |
          npm init -y
          npm install --save-dev @axe-core/cli http-server
      - name: Start local server
        run: npx http-server _site -p 3000 &
      - name: Wait for server
        run: sleep 5
      - name: Run accessibility tests
        run: npx axe http://localhost:3000 --exit --config test/.axerc.json

  # Run visual and composition tests with Chromatic (if using Storybook)
  visual-and-composition:
    runs-on: ubuntu-latest
    needs: build
    if: false # Disable unless you have Storybook setup
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  # Run user flow tests with Cypress
  user-flow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: jekyll-site
          path: _site/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Cypress
        run: |
          npm init -y
          npm install --save-dev cypress http-server
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config-file: test/cypress.config.js
          start: npx http-server _site -p 3000
          wait-on: 'http://localhost:3000'
          browser: chrome